# Generated by Django 5.2.8 on 2025-11-28 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="TMDB ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="电影名称")),
                (
                    "image_link",
                    models.URLField(max_length=500, verbose_name="封面图片链接"),
                ),
                (
                    "country",
                    models.CharField(max_length=100, verbose_name="制片国家/地区"),
                ),
                ("years", models.CharField(max_length=10, verbose_name="年代")),
                (
                    "director_description",
                    models.CharField(blank=True, max_length=500, verbose_name="导演"),
                ),
                (
                    "leader",
                    models.CharField(blank=True, max_length=1000, verbose_name="主演"),
                ),
                ("star", models.FloatField(default=0.0, verbose_name="TMDB评分")),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "alltags",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="类型标签"
                    ),
                ),
                (
                    "imdb",
                    models.CharField(blank=True, max_length=50, verbose_name="IMDb ID"),
                ),
                (
                    "language",
                    models.CharField(blank=True, max_length=50, verbose_name="语言"),
                ),
                (
                    "time_length",
                    models.CharField(blank=True, max_length=50, verbose_name="时长"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="浏览量")),
            ],
            options={
                "verbose_name": "电影",
                "verbose_name_plural": "电影列表",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(verbose_name="评分")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="评分时间"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="电影",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户评分",
                "verbose_name_plural": "用户评分列表",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        verbose_name="电影",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏列表",
                "unique_together": {("user", "movie")},
            },
        ),
    ]
